project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
#from tasks.views import index
from tasks import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls'))
]

quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    #CREATE FBV
    path('bugs/new/', views.add_bug_report, name='create_bug_report'),
    path('features/new/', views.add_feature_request, name='create_feature_request'),

    #CREATE CBV
    path('bugs/new/', views.BugReportCreateView.as_view(), name='create_bug_report'),
    path('features/new/', views.FeatureRequestCreateView.as_view(), name='create_feature_request'),


    #READ FBV
    path('', views.index, name='index'),
    path('bugs/', views.bug_list, name='bugs_page'),
    path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail_page'),
    path('features/', views.feature_list, name='features_page'),
    path('features/<int:feature_id>/', views.feature_detail, name='feature_detail_page'),

    #READ CBV
    path('', views.IndexView.as_view(), name='index'),
    path('bugs/', views.BugListView.as_view(), name='bugs_page'),
    path('bugs/<int:bug_id>/', views.BugDetailView.as_view(), name='bug_detail_page'),
    path('features/', views.FeatureListView.as_view(), name='features_page'),
    path('features/<int:feature_id>/', views.FeatureRequestDetailView.as_view(), name='feature_detail_page'),


    #UPDATE FBV
    path('bugs/<int:bug_id>/update', views.update_bug_report, name='update_bug_report'),
    path('features/<int:feature_id>/update', views.update_feature_request, name='update_feature_request'),

    #UPDATE CBV
    path('bugs/<int:bug_id>/update', views.BugReportUpdateView.as_view(), name='update_bug_report'),
    path('features/<int:feature_id>/update', views.FeatureRequestUpdateView.as_view(), name='update_feature_request'),


    #DELETE FBV
    path('bugs/<int:bug_id>/delete', views.delete_bug_report, name='delete_bug_report'),
    path('features/<int:feature_id>/delete', views.delete_feature_request, name='delete_feature_request'),

    #DELETE FBV
    #path('bugs/<int:bug_id>/delete', views.BugReportDeleteView.as_view(), name='delete_bug_report'),
    #path('features/<int:feature_id>/delete', views.FeatureRequestDeleteView.as_view(), name='delete_feature_request'),
]

tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    #READ FBV
    #path('', views.index),
    #path('projects/', views.projects_list, name='projects_list'),
    #path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    #path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),

    #READ CBV
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),

    #CREATE FBV
    path('feedback/', views.feedback_view, name='feedback'),
    #path('project/new/', views.create_project, name='create_project'),
    #path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),

    #CREATE CBV
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),

    #UPDATE FBV
    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),

    #UPDATE CBV
    #path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    #path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),

    #DELETE FBV
    #path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    #path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),

    #DELETE CBV
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

quality_control/models.py
from django.db import models
from tasks.models import Project, Task


class BugReport(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    PRIORITY_CHOICES = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
    )
    priority = models.PositiveSmallIntegerField(
        choices=PRIORITY_CHOICES,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

class FeatureRequest(models.Model):
    STATUS_CHOICES = [
        ('Consideration', 'Расмотрение'),
        ('Accepted', 'Принято'),
        ('Declined', 'Отклонено'),
    ]
    PRIORITY_CHOICES = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status=models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
    )
    priority = models.PositiveSmallIntegerField(
        choices=PRIORITY_CHOICES,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

quality_control/forms.py
from django import forms
from django.forms import ModelForm
from .models import BugReport, FeatureRequest


class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']


class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

quality_control/views.py
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import View
from django.shortcuts import get_object_or_404
from .models import BugReport, FeatureRequest
from django.views.generic import ListView, DetailView, CreateView
from django.shortcuts import render, redirect
from .forms import BugReportForm, FeatureRequestForm
from django.views.generic.edit import UpdateView, DeleteView


#CREATE FBV
def add_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            bug = form.save(commit=False)
            bug.save()
            return redirect('quality_control:bugs_page')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})

def add_feature_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            feature = form.save(commit=False)
            feature.save()
            return redirect('quality_control:features_page')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})

#CREATE CBV
class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control:bugs_page')

class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = ('quality_control/feature_request_form.html')
    success_url = reverse_lazy('quality_control:features_page')

#READ FBV
def index(request):
    return render(request, 'quality_control/index.html')

def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bug_list': bugs})

def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bug': bug})


def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'feature_list': features})

def feature_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature})



#READ CBV
class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')

class BugListView(ListView):
    model = BugReport
    template_name = 'quality_control/bug_list.html'
    context_object_name = ('bug_list')

class BugDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_detail.html'
    context_object_name = 'bug'

class FeatureListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/feature_list.html'
    context_object_name = 'feature_list'

class FeatureRequestDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_detail.html'
    context_object_name = 'feature'

#UPDATE FBV
def update_bug_report(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            bug = form.save(commit=False)
            bug.save()
            return redirect('quality_control:bugs_page')
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_report_update.html', {'form': form, 'bug': bug})

def update_feature_request(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            feature = form.save(commit=False)
            feature.save()
            return redirect('quality_control:features_page')
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_request_update.html', {'form': form, 'feature': feature})


#UPDATE CBV
class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bugs_page')

class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:features_page')


#DELETE FBV
def delete_bug_report(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bugs_page')

def delete_feature_request(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:features_page')

#DELETE CBV
class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    context_object_name = 'bug'
    success_url = reverse_lazy('quality_control:bugs_page')
    template_name = 'quality_control/bug_report_confirm_delete.html'

class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    context_object_name = 'feature'
    success_url = reverse_lazy('quality_control:features_page')
    template_name = 'quality_control/feature_request_confirm_delete.html'

quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}

    <h1>{{ bug.title }}</h1>

    <a href="{% url 'quality_control:update_bug_report' bug.id %}">Изменить отчёт о баге</a>
    <p><a href="{% url 'quality_control:delete_bug_report' bug.id %}" onclick="return confirm('Вы уверены, что хотите удалить этот отчёт?');">Удалить отчёт о баге</a></p>

    <p>Description: {{ bug.description }}</p>
    <p>Priority: {{ bug.priority }}</p>
    <p><a href="{% url 'tasks:project_detail' bug.project.id %}">Related project: {{ bug.project }}</a></p>
    <p><a href="{% url 'tasks:task_detail' bug.project.id bug.task.id %}">Related task: {{ bug.task }}</a></p>

{% endblock %}

quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список багов</h1>

    <p><a href="{% url 'quality_control:create_bug_report' %}">Создать новый отчёт о баге</a></p>

    <ul>
        {% for bug in bug_list %}
            <li><a href="{% url 'quality_control:bug_detail_page' bug.id %}">{{ bug.title }}</a> - {{ bug.status }}</li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/bug_report_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление отчёта о баге</h1>
    <p>Вы уверены, что хотите удалить отчёт "{{ bug.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug_report' bug.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail_page' bug.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Добавить отчёт о баге в проект</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать отчёт</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_report_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение отчёта о баге: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}

    <h1>{{ feature.title }}</h1>

    <a href="{% url 'quality_control:update_feature_request' feature.id %}">Изменить запрос на улучшение</a>
    <p><a href="{% url 'quality_control:delete_feature_request' feature.id %}" onclick="return confirm('Вы уверены, что хотите удалить этот запрос?');">Удалить запрос на улучшение</a></p>

    <p>Description: {{ feature.description }}</p>
    <p>Priority: {{ feature.priority }}</p>
    <p><a href="{% url 'tasks:project_detail' feature.project.id %}">Related project: {{ feature.project.name }}</a></p>
    <p><a href="{% url 'tasks:task_detail' feature.project.id feature.task.id %}">Related task: {{ feature.task.name }}</a></p>

{% endblock %}

quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>

     <p><a href="{% url 'quality_control:create_feature_request' %}">Создать новый запрос на улучшение</a></p>

    <ul>
        {% for feature in feature_list %}
            <li><a href="{% url 'quality_control:feature_detail_page' feature.id %}">{{ feature.title }}</a> - {{feature.status}}</li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/feature_request_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос "{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature_request' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail_page' feature.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Добавить запрос на улучшение в проект</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать запрос</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_request_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ feature.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Страница приложения quality_control</h1>
        <ul>
        <li><a href="{% url 'quality_control:bugs_page' %}">Список багов</a></li>
        <li><a href="{% url 'quality_control:features_page' %}">Список запросов на улучшения</a></li>
        </ul>
{% endblock %}